image:
  file: .gitpod.dockerfile

ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - name: Build wasm files
    init:  >
      cd $HOME/emsdk &&
      . ./emsdk_env.sh &&
      cd /workspace/dedx_web/ &&
      ./build_wasm.sh &&
      gp sync-done wasm

  - name: install npm deps 
    init: > 
      npm install &&
      gp sync-done deps

  - name: start dev server
    command: > 
      gp await-done wasm &&
      gp await-done deps &&
      npm run start